# Generated by Django 4.0.4 on 2022-04-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0003_alter_bouquet_frech_period_alter_bouquet_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='delivered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
